// Code generated by entc, DO NOT EDIT.

package groupmember

const (
	// Label holds the string label denoting the groupmember type in the database.
	Label = "group_member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldMemberID holds the string denoting the member_id field in the database.
	FieldMemberID = "member_id"
	// Table holds the table name of the groupmember in the database.
	Table = "group_member"
)

// Columns holds all SQL columns for groupmember fields.
var Columns = []string{
	FieldID,
	FieldGroupID,
	FieldMemberID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
