// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package constructor

import (
	"github.com/AkiOuma/biz-groups/internal/domain/service"
	"github.com/AkiOuma/biz-groups/internal/infrastructure/component"
	"github.com/AkiOuma/biz-groups/internal/infrastructure/config"
	"github.com/AkiOuma/biz-groups/internal/interface/datasource"
	"github.com/AkiOuma/biz-groups/internal/interface/datasource/sqldb"
	"github.com/AkiOuma/biz-groups/internal/interface/transport"
	"github.com/AkiOuma/biz-groups/internal/usecase"
)

// Injectors from wire.go:

func InitApp(bootstrap *config.Bootstrap) *component.GrpcServer {
	client := component.NewEntClient(bootstrap)
	db := sqldb.NewDB(client)
	repository := datasource.NewDatasource(db)
	serviceService := service.NewService(repository)
	usecaseUsecase := usecase.NewUsecase(repository, serviceService)
	transportTransport := transport.NewTransport(usecaseUsecase)
	grpcServer := component.NewGrpcServer(transportTransport, bootstrap)
	return grpcServer
}
