// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/AkiOuma/biz-groups/internal/interface/datasource/sqldb/ent/runtime.go

const (
	Version = "v0.10.1"                                         // Version of ent codegen.
	Sum     = "h1:dM5h4Zk6yHGIgw4dCqVzGw3nWgpGYJiV4/kyHEF6PFo=" // Sum of ent codegen.
)
