// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupMember is the predicate function for groupmember builders.
type GroupMember func(*sql.Selector)
